name: zawadi
description: "Browse and discover a wide selection of digital gift cards from popular retailers, restaurants, and online stores in Tanzania."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_fonts: 6.1.0
  device_preview: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Zawadi
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  image_picker: ^0.8.7
  persistent_bottom_nav_bar: ^5.0.2
  firebase_crashlytics: ^3.4.18
  firebase_app_check: ^0.2.1+17
  firebase_remote_config: ^4.3.17
  flutter_animate: ^4.5.0
  firebase_analytics: ^10.8.9
  top_snackbar_flutter: ^3.1.0
  flutter_gen: ^5.4.0
  build_runner:
  go_router: ^13.2.2
  shared_preferences: ^2.2.3
  flutter_gen_runner: ^5.4.0
  flutter_riverpod: ^2.5.1
  uuid: ^4.3.3
  riverpod_annotation:
  flutterwave_standard: ^1.0.8
  intl: 0.18.1
  lottie: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  http: ^1.2.0
  flutter_screenutil: ^5.5.3+2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  isar: 3.1.0
  dartz: ^0.10.1
  analyzer: 5.13.0
  isar_flutter_libs: 3.1.0
  path_provider: ^2.1.3
  riverpod_generator:
  hooks_riverpod:
  isar_generator: 3.1.0



  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.7.0
  badges: ^3.1.2

  flutter_native_splash: ^2.1.1
  provider: ^6.1.1
  location: ^5.0.3
  permission_handler: ^11.2.0
  google_maps_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0

  string_validator: ^1.0.2
  flutter_timer_countdown: ^1.0.7

  #cloud_firestore: ^4.15.8
  dropdown_button2: ^2.0.0
  firebase_database: ^10.0.16
  firebase_storage: ^11.0.15
  flutter_launcher_icons: ^0.13.1
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.1
  internet_connection_checker_plus: ^2.2.0


  flutter_slidable:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner:
  freezed: ^2.5.2
  analyzer: 5.13.0
  riverpod_generator:

scripts: zawadi.yaml

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #config files
    - .env
    - zawadi.yaml

    #fonts
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/errors/
    - assets/images/categories/
    - assets/images/cardthemes/
    - assets/prints/
    - assets/icon/
    - assets/lotties/
    - assets/svgs/

  fonts:
    - family: QrooFont
      fonts:
        - asset: assets/fonts/QrooRegular.ttf
        - asset: assets/fonts/QrooBold.ttf
          weight: 700
        - asset: assets/fonts/QrooLight.ttf
          weight: 300

    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Regular.otf

    - family: Questrial
      fonts:
        - asset: assets/fonts/Questrial-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Halter
      fonts:
        - asset: assets/fonts/halter.ttf


  # Card custom fonts
    - family: Parisienne
      fonts:
        - asset: assets/fonts/Parisienne-Regular.ttf

    - family: Klein
      fonts:
        - asset: assets/fonts/Klein-Regular.ttf

    - family: Frunchy
      fonts:
        - asset: assets/fonts/Frunchy-Sage.ttf

    - family: Blueberry
      fonts:
        - asset: assets/fonts/Blueberry.ttf
